apiVersion: build.knative.dev/v1alpha1
kind: BuildTemplate
metadata:
  name: kanikythe
spec:
  parameters:
  - name: IMAGE
    description: The name of the image to push
  - name: PACKAGE
    description: The go package to index
  steps:
  - name: pull-dockerfiles
    image: gcr.io/jonjohnson-test/kythe/base
  - name: index-source
    image: gcr.io/kaniko-project/executor
    args:
    - --dockerfile=/workspace/builder/Dockerfile
    - --build-arg=PACKAGE=${PACKAGE}
    - --no-push
  - name: build-and-push-web
    image: gcr.io/kaniko-project/executor
    args:
    - --dockerfile=/workspace/web/Dockerfile
    - --destination=${IMAGE}
